# Generated by Django 5.0.4 on 2024-05-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_deparment_id_departments_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='department_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='id',
        ),
    ]
